CREATE DATABASE persono_post;

CREATE SCHEMA post;

CREATE TABLE post.T_PER_POST (
    ID_POST              INT,
    DS_TITLE             VARCHAR(150),
    NM_AUTHOR       	 VARCHAR(50),
    DS_CONTENTS          VARCHAR(200),
    NM_CATEGORY          VARCHAR(25),
    DT_CREATED_AT        DATE
);

ALTER TABLE post.T_PER_POST ADD CONSTRAINT PK_PER_POST
PRIMARY KEY (ID_POST);

ALTER TABLE post.T_PER_POST
ALTER COLUMN ID_POST ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE post.T_PER_POST
ALTER COLUMN DS_TITLE SET NOT NULL;
ALTER TABLE post.T_PER_POST
ALTER COLUMN NM_AUTHOR SET NOT NULL;
ALTER TABLE post.T_PER_POST
ALTER COLUMN DS_CONTENTS SET NOT NULL;
ALTER TABLE post.T_PER_POST
ALTER COLUMN NM_CATEGORY SET NOT NULL;
ALTER TABLE post.T_PER_POST
ALTER COLUMN DT_CREATED_AT SET NOT NULL;

ALTER TABLE post.T_PER_POST
ALTER COLUMN DT_CREATED_AT SET DEFAULT CURRENT_DATE;

COMMENT ON COLUMN post.T_PER_POST.ID_POST IS
    'Esse atributo irá receber a chave primária do post. Esse número é sequencia e gerado automaticamente pelo sistema. Seu conteúdo é obrigatório.';
COMMENT ON COLUMN post.T_PER_POST.DS_TITLE IS
    'Esse atributo irá receber o título referente ao post. Seu conteúdo é obrigatório.';
COMMENT ON COLUMN post.T_PER_POST.NM_AUTHOR IS
    'Esse atributo irá receber o nome do autor do post. Seu conteúdo é obrigatório.';
COMMENT ON COLUMN post.T_PER_POST.DS_CONTENTS IS
    'Esse atributo irá receber o conteúdo do post. Seu conteúdo é obrigatório.';
COMMENT ON COLUMN post.T_PER_POST.NM_CATEGORY IS
    'Esse atributo irá receber a categoria do post. Seu conteúdo é obrigatório.';
COMMENT ON COLUMN post.T_PER_POST.DT_CREATED_AT IS
    'Esse atributo irá armazenar a data do post. Seu conteúdo é obrigatório.';
